# 是否启用 bStats 数据统计
use-bstats: true

# 是否使用 Bukkit 的广播 API (推荐 true，性能更好 Folia是否启用无所谓)
use-bukkit-api: true

# 文件自动侦测热更新
auto-reload-enabled: true

# 头像占位符 (在聊天格式中使用这个变量)
head-placeholder: "%player_head%"

# 聊天消息格式
# %flux_qx%-生物群系 %player_name%-玩家名 %message%-发送的消息
chat-format: '[&e%player_ping%ms %flux_qx%&f &d%statistic_time_played:hours%h&f]%player_name%&6>>&f%message%'

#前置 PlaceholderAPI
#/papi ecloud download Player -第一步
#/papi ecloud download Server -第二步
#/papi ecloud download Statistic -第三步
#/papi reload -最后